services:
  mongodb:
    image: mongo:6.0  # Usa MongoDB 6.0
    container_name: mongodb  # Nombre fijo del contenedor
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - "${MONGO_DATA_DIR}:/data/db"  # Datos persistentes
      - "${MONGO_CONFIG_DIR}:/etc/mongo"  # Configuraciones
      - "${MONGO_LOGS_DIR}:/var/log/mongodb"  # Logs
    command:
      - "--wiredTigerCacheSizeGB=4"
      - "--port=${MONGO_PORT}"
    networks:
      - mongo_net

networks:
  mongo_net:
    driver: bridge
